### ISSUE TITLE
PhoneBetaFeedback Crash on open

### ISSUE THREAD

**Issue by Belbertn** [ferasm/reddhub#310]
The app crashes right after I open it. Before I get the chance to open a subreddit etc

**Comment by JDOfTheNorth** [comment]
Thanks for the heads up.  Investigating ...

**Comment by JDOfTheNorth** [comment]
We've found the bug causing this, and pushed an update to the store. It should be live in a couple of hours. Please uninstall and reinstall the app, and that should fix the problem. 

Thanks again for reporting this! It's exactly these types of issues we want to make sure get ironed in testing, so that we can have a successful launch :)

**Comment by Belbertn** [comment]
Thanks alot! I love the app :)
