### ISSUE TITLE
PhoneBetaFeedbackCrash on start when logged it

### ISSUE THREAD

**Issue by sirfergy** [ferasm/reddhub#311]
On Windows phone 10, app crashes after I login in.

**Comment by sirfergy** [comment]
If I'm not logged in app does not crash

**Comment by JDOfTheNorth** [comment]
Thanks for the heads up.  We're looking into this right now ...

**Comment by JDOfTheNorth** [comment]
We've found the bug causing this, and pushed an update to the store. It should be live in a couple of hours. Please uninstall and reinstall the app, and that should fix the problem. 

Thanks again for reporting this! It's exactly these types of issues we want to make sure get ironed in testing, so that we can have a successful launch :)
